
include $(GOROOT)/src/Make.$(GOARCH)

TARG=thrift/protocol
GOFILES=\
        tbinary_protocol.go\
        tcompact_protocol.go\
        tcompare.go\
        tcontainer.go\
        tfield.go\
        tlist.go\
        tnumeric.go\
        tmap.go\
        tmessage.go\
        tmessagetype.go\
        tprotocol.go\
        tprotocol_exception.go\
        tprotocol_factory.go\
        tset.go\
        tsimple_json_protocol.go\
        tstruct.go\
        ttype.go

DIRS=\

include $(GOROOT)/src/Make.pkg
