
include $(GOROOT)/src/Make.inc

TARG=thrift/transport
GOFILES=\
        tframed_transport.go\
        thttp_client.go\
        tiostream_transport.go\
        tmemory_buffer.go\
        tnonblocking_server_socket.go\
        tnonblocking_socket.go\
        tnonblocking_transport.go\
        tserver_socket.go\
        tserver_transport.go\
        tsocket.go\
        ttransport.go\
        ttransport_exception.go\
        ttransport_factory.go

DIRS=\

include $(GOROOT)/src/Make.pkg
