
include $(GOROOT)/src/Make.inc

all: install

TARG=thriftlib/simple

DIRS=\
  ContainerOfEnumsTestService\

GOFILES=\
  ttypes.go\
  ContainerOfEnumsTestService.go\


include $(GOROOT)/src/Make.pkg

