
include $(GOROOT)/src/Make.inc

TARG=thrift/base
GOFILES=\
        tbase.go\
        tprocessor.go\
        tprocessor_factory.go\
        tapplication_exception.go\

DIRS=\

include $(GOROOT)/src/Make.pkg
